{
  "formatVersion": "1.1",
  "component": {
    "group": "com.imf.so",
    "module": "load-hook",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "load-hook-0.0.9.jar",
          "url": "load-hook-0.0.9.jar",
          "size": 2349,
          "sha512": "298178cc770aaeb43088afe7efded56e19fe19258e98aa75184e802d863a13426e182d2ea8a07cbaff927e524fa59c20a3143684d54897133bb6590f12ceb2a7",
          "sha256": "0c277ba78ac1102efce6b05030d6b467c495f77e7501e1d84cef20382a8d575a",
          "sha1": "76633881caf78920a8c0eb4c379ecd1529fba9b6",
          "md5": "5f8c22ab3426ab648ac9170798f7f0ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "load-hook-0.0.9.jar",
          "url": "load-hook-0.0.9.jar",
          "size": 2349,
          "sha512": "298178cc770aaeb43088afe7efded56e19fe19258e98aa75184e802d863a13426e182d2ea8a07cbaff927e524fa59c20a3143684d54897133bb6590f12ceb2a7",
          "sha256": "0c277ba78ac1102efce6b05030d6b467c495f77e7501e1d84cef20382a8d575a",
          "sha1": "76633881caf78920a8c0eb4c379ecd1529fba9b6",
          "md5": "5f8c22ab3426ab648ac9170798f7f0ad"
        }
      ]
    }
  ]
}
