{
  "formatVersion": "1.1",
  "component": {
    "group": "com.imf.so",
    "module": "load-hook",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "load-hook-0.0.9.jar",
          "url": "load-hook-0.0.9.jar",
          "size": 2349,
          "sha512": "d3d44f58bb51aab273c029c53c18fad8622e73c5928c601d0a54a9ff83571aae19994bfd4c52a67d936ef22c7889bc6633dd44cc5347b35a757213e1d0e4fada",
          "sha256": "0826b3ea6159644e4fc2f2fbbb97dfb69fbb3da7955b2c6138e3c346a2a90376",
          "sha1": "229a4192178b372848fcdf87660546075def106b",
          "md5": "2845c5218f50f5a07809cdc0319d5254"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "load-hook-0.0.9.jar",
          "url": "load-hook-0.0.9.jar",
          "size": 2349,
          "sha512": "d3d44f58bb51aab273c029c53c18fad8622e73c5928c601d0a54a9ff83571aae19994bfd4c52a67d936ef22c7889bc6633dd44cc5347b35a757213e1d0e4fada",
          "sha256": "0826b3ea6159644e4fc2f2fbbb97dfb69fbb3da7955b2c6138e3c346a2a90376",
          "sha1": "229a4192178b372848fcdf87660546075def106b",
          "md5": "2845c5218f50f5a07809cdc0319d5254"
        }
      ]
    }
  ]
}
