{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mainlxl.Android-So-Handler",
    "module": "file-plugin",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "file-plugin-0.0.11.jar",
          "url": "file-plugin-0.0.11.jar",
          "size": 75225,
          "sha512": "961789adaa1dd7f2c95ad288d208880dcab995edac477103df26fcef2b6031ef0ade7a27c9518f7b79f7ea7934f50091c1992d6865034630d9c0de26c3f14214",
          "sha256": "8a523ce3fc746283a193197407dccc8aab54be4b558546d2be151d74c3d16a3e",
          "sha1": "72317a699184ea813aa0b2e7ed322513b519af26",
          "md5": "42ce9f59a2043016fa036f158763a14c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.gradle",
          "module": "osdetector-gradle-plugin",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.apktool",
          "module": "apktool-lib",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "file-plugin-0.0.11.jar",
          "url": "file-plugin-0.0.11.jar",
          "size": 75225,
          "sha512": "961789adaa1dd7f2c95ad288d208880dcab995edac477103df26fcef2b6031ef0ade7a27c9518f7b79f7ea7934f50091c1992d6865034630d9c0de26c3f14214",
          "sha256": "8a523ce3fc746283a193197407dccc8aab54be4b558546d2be151d74c3d16a3e",
          "sha1": "72317a699184ea813aa0b2e7ed322513b519af26",
          "md5": "42ce9f59a2043016fa036f158763a14c"
        }
      ]
    }
  ]
}
