{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mainlxl.Android-So-Handler",
    "module": "load-hook-plugin",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "load-hook-plugin-0.0.11.jar",
          "url": "load-hook-plugin-0.0.11.jar",
          "size": 34337,
          "sha512": "86110296fb6708e3259e2a9ddfb6715d03c7fad6f6173d272d5d6a3b5daa2394f322ce9dc86d4e7993d7bf38faddfd86e54f08df04a340e0c5c98099e70531f6",
          "sha256": "e67d2e7d254494b5f3c5705476f1d5757a5cf21702601314bb1c794f87a0de16",
          "sha1": "5165f0f2bf9f7bed433b697642daa64120c75026",
          "md5": "bd7404d963c32796b79cb8a31740c88d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.3.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "load-hook-plugin-0.0.11.jar",
          "url": "load-hook-plugin-0.0.11.jar",
          "size": 34337,
          "sha512": "86110296fb6708e3259e2a9ddfb6715d03c7fad6f6173d272d5d6a3b5daa2394f322ce9dc86d4e7993d7bf38faddfd86e54f08df04a340e0c5c98099e70531f6",
          "sha256": "e67d2e7d254494b5f3c5705476f1d5757a5cf21702601314bb1c794f87a0de16",
          "sha1": "5165f0f2bf9f7bed433b697642daa64120c75026",
          "md5": "bd7404d963c32796b79cb8a31740c88d"
        }
      ]
    }
  ]
}
