{
  "formatVersion": "1.1",
  "component": {
    "group": "com.imf.so",
    "module": "file-plugin",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "file-plugin-0.0.9.jar",
          "url": "file-plugin-0.0.9.jar",
          "size": 63610,
          "sha512": "eb992ba3e78a59b2cdb879e4e6f75b2c3ce8976501bd83b341a55e15feb758537de25c91c9b83504c20fbab477088d60119e0b19226571cb77ebebaf577fdd47",
          "sha256": "f592026a3c335318e6a85b1f1e09a8c0ebf4905c14d23d6899a10375255ccbc4",
          "sha1": "bd9a81684837c08d0dae42053c5aac95136cd700",
          "md5": "98e9fc7a9033f82fc63375c808af5821"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.gradle",
          "module": "osdetector-gradle-plugin",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "file-plugin-0.0.9.jar",
          "url": "file-plugin-0.0.9.jar",
          "size": 63610,
          "sha512": "eb992ba3e78a59b2cdb879e4e6f75b2c3ce8976501bd83b341a55e15feb758537de25c91c9b83504c20fbab477088d60119e0b19226571cb77ebebaf577fdd47",
          "sha256": "f592026a3c335318e6a85b1f1e09a8c0ebf4905c14d23d6899a10375255ccbc4",
          "sha1": "bd9a81684837c08d0dae42053c5aac95136cd700",
          "md5": "98e9fc7a9033f82fc63375c808af5821"
        }
      ]
    }
  ]
}
