{
  "formatVersion": "1.1",
  "component": {
    "group": "com.imf.so",
    "module": "file-plugin",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "file-plugin-0.0.9.jar",
          "url": "file-plugin-0.0.9.jar",
          "size": 63610,
          "sha512": "42996573ffa68a25d0bc5fabf05a24b1022990ce322422a79540b4308f1c23bdccfc709d04ab4980619dc5003b6096ab6e5f3b4ae85877c54402f17c10f23ead",
          "sha256": "2dae49312f1402a633dea7fb6f1209ef36bab0a081e6fb0c73f3627bbc45f76f",
          "sha1": "0345049a5ac33cb6388d757cc33887452c27275d",
          "md5": "70f70a1ae1ceaa03bd5018fda4a86643"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.gradle",
          "module": "osdetector-gradle-plugin",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "file-plugin-0.0.9.jar",
          "url": "file-plugin-0.0.9.jar",
          "size": 63610,
          "sha512": "42996573ffa68a25d0bc5fabf05a24b1022990ce322422a79540b4308f1c23bdccfc709d04ab4980619dc5003b6096ab6e5f3b4ae85877c54402f17c10f23ead",
          "sha256": "2dae49312f1402a633dea7fb6f1209ef36bab0a081e6fb0c73f3627bbc45f76f",
          "sha1": "0345049a5ac33cb6388d757cc33887452c27275d",
          "md5": "70f70a1ae1ceaa03bd5018fda4a86643"
        }
      ]
    }
  ]
}
