{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mainlxl.Android-So-Handler",
    "module": "file-plugin",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "file-plugin-0.0.12.jar",
          "url": "file-plugin-0.0.12.jar",
          "size": 76005,
          "sha512": "7f2b2d810d82bfbd631e589b28d480059ca99368b1d82333a4faac85b1f2cf27a7f177dae88eb003f10296e0296a5979e885307c8e3831be08ed614911f8ca1f",
          "sha256": "bc0dff602d43c4b1d185613b8fceb3b922449b0d319de84662af3aa1e947ff44",
          "sha1": "023fdbea6a2e7f56b18fed4825c95fc4d2b02789",
          "md5": "f51043957a007e6c44958736e5e42541"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.gradle",
          "module": "osdetector-gradle-plugin",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.apktool",
          "module": "apktool-lib",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "file-plugin-0.0.12.jar",
          "url": "file-plugin-0.0.12.jar",
          "size": 76005,
          "sha512": "7f2b2d810d82bfbd631e589b28d480059ca99368b1d82333a4faac85b1f2cf27a7f177dae88eb003f10296e0296a5979e885307c8e3831be08ed614911f8ca1f",
          "sha256": "bc0dff602d43c4b1d185613b8fceb3b922449b0d319de84662af3aa1e947ff44",
          "sha1": "023fdbea6a2e7f56b18fed4825c95fc4d2b02789",
          "md5": "f51043957a007e6c44958736e5e42541"
        }
      ]
    }
  ]
}
