{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mainlxl.Android-So-Handler",
    "module": "file-plugin",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "file-plugin-0.0.12.jar",
          "url": "file-plugin-0.0.12.jar",
          "size": 76013,
          "sha512": "7f3d6ce83105a04369b1054f0a8cb47d10a3861d6418c5ce8dd7457ebc04036d8073805f08bc6d171638d3739aefa422434f04b69e39c5aa9197916a6d95935b",
          "sha256": "fbcb891217c0bb0f54faf156c80fdf1931ef521058b155f74b7da2a3b7ea6ca6",
          "sha1": "e7ac408dbc8827bd21bfd7fd136404e2384184de",
          "md5": "97a6d910de9ec3792d6ac1ec3233716b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.gradle",
          "module": "osdetector-gradle-plugin",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.apktool",
          "module": "apktool-lib",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "file-plugin-0.0.12.jar",
          "url": "file-plugin-0.0.12.jar",
          "size": 76013,
          "sha512": "7f3d6ce83105a04369b1054f0a8cb47d10a3861d6418c5ce8dd7457ebc04036d8073805f08bc6d171638d3739aefa422434f04b69e39c5aa9197916a6d95935b",
          "sha256": "fbcb891217c0bb0f54faf156c80fdf1931ef521058b155f74b7da2a3b7ea6ca6",
          "sha1": "e7ac408dbc8827bd21bfd7fd136404e2384184de",
          "md5": "97a6d910de9ec3792d6ac1ec3233716b"
        }
      ]
    }
  ]
}
