{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mainlxl.Android-So-Handler",
    "module": "file-plugin",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "file-plugin-0.0.12.jar",
          "url": "file-plugin-0.0.12.jar",
          "size": 75995,
          "sha512": "d95721639bb79e99cdfa92bf82edf473c808764fa92d459d0eae47fa8060e2a24a56e0cec16d185323d9bb168443f3f390c0d5fda681f76eb16482615a08227e",
          "sha256": "113608ae398ca7e887ae358d9052c96868a831d56a966e5c200c86940804af9c",
          "sha1": "07b82a132b52321d4e0cc9e63a6b6d47ad46d296",
          "md5": "e01c98c5856a28df9e2457ab5f302e36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.gradle",
          "module": "osdetector-gradle-plugin",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.apktool",
          "module": "apktool-lib",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "file-plugin-0.0.12.jar",
          "url": "file-plugin-0.0.12.jar",
          "size": 75995,
          "sha512": "d95721639bb79e99cdfa92bf82edf473c808764fa92d459d0eae47fa8060e2a24a56e0cec16d185323d9bb168443f3f390c0d5fda681f76eb16482615a08227e",
          "sha256": "113608ae398ca7e887ae358d9052c96868a831d56a966e5c200c86940804af9c",
          "sha1": "07b82a132b52321d4e0cc9e63a6b6d47ad46d296",
          "md5": "e01c98c5856a28df9e2457ab5f302e36"
        }
      ]
    }
  ]
}
