{
  "formatVersion": "1.1",
  "component": {
    "group": "com.imf.so",
    "module": "android-un7z",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-un7z-0.0.8.aar",
          "url": "android-un7z-0.0.8.aar",
          "size": 161771,
          "sha512": "1288ca3b5fc8f362b3b4c14751cd1f3154edde97cc31597ef44c3f5b04c3ec6c5b9a5aa9c5246c2a530b8cf1c2e9f7a9f347bb134e90ce0b6142085a904342d2",
          "sha256": "1c3ed5f612f47b61a6d27181295f5df8f2b937b790376d834b6f4a2fe0a03a16",
          "sha1": "b73ffdad127ef9888caf8056e618911021f34671",
          "md5": "fd3b45ad69b70670aa301c6bb224dab3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-un7z-0.0.8.aar",
          "url": "android-un7z-0.0.8.aar",
          "size": 161771,
          "sha512": "1288ca3b5fc8f362b3b4c14751cd1f3154edde97cc31597ef44c3f5b04c3ec6c5b9a5aa9c5246c2a530b8cf1c2e9f7a9f347bb134e90ce0b6142085a904342d2",
          "sha256": "1c3ed5f612f47b61a6d27181295f5df8f2b937b790376d834b6f4a2fe0a03a16",
          "sha1": "b73ffdad127ef9888caf8056e618911021f34671",
          "md5": "fd3b45ad69b70670aa301c6bb224dab3"
        }
      ]
    }
  ]
}
