{
  "formatVersion": "1.1",
  "component": {
    "group": "com.imf.so",
    "module": "load-hook-plugin",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "load-hook-plugin-0.0.9.jar",
          "url": "load-hook-plugin-0.0.9.jar",
          "size": 34337,
          "sha512": "a01816affece06e28b31675b843a094eb4a476ffda442c33faf6a6fa38b9697137b338512bee84c2db183de82a0f67e51dbecfd9745df6ba09f94d88522e44f0",
          "sha256": "841bf36757244520c3dc54c55239dbeefa4e53e722b183fd00fa45f34fe330e7",
          "sha1": "05b6369ce6bcb6e29336da13ebf0743582c123d0",
          "md5": "d3c7e292f24d9925416c31375a606692"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.3.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "load-hook-plugin-0.0.9.jar",
          "url": "load-hook-plugin-0.0.9.jar",
          "size": 34337,
          "sha512": "a01816affece06e28b31675b843a094eb4a476ffda442c33faf6a6fa38b9697137b338512bee84c2db183de82a0f67e51dbecfd9745df6ba09f94d88522e44f0",
          "sha256": "841bf36757244520c3dc54c55239dbeefa4e53e722b183fd00fa45f34fe330e7",
          "sha1": "05b6369ce6bcb6e29336da13ebf0743582c123d0",
          "md5": "d3c7e292f24d9925416c31375a606692"
        }
      ]
    }
  ]
}
