{
  "formatVersion": "1.1",
  "component": {
    "group": "com.imf.so",
    "module": "load-hook-plugin",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "load-hook-plugin-0.0.9.jar",
          "url": "load-hook-plugin-0.0.9.jar",
          "size": 34337,
          "sha512": "8d81e92b2250968f9d68eb71cc1eb919bf1690e026ec97751aad4df501653c0381a6ad2d2594f39fa411b8ff681104fb7489077c12865d75de7e823c32c41f01",
          "sha256": "42789faade618d530f858034360a68aa4b0a417931846992137a5b1ea4f4a969",
          "sha1": "21e722aeb667c6e32ed2936e80fc76f1963bb577",
          "md5": "ffc6e358f8001c2e5ddce320eb73fe3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.3.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "load-hook-plugin-0.0.9.jar",
          "url": "load-hook-plugin-0.0.9.jar",
          "size": 34337,
          "sha512": "8d81e92b2250968f9d68eb71cc1eb919bf1690e026ec97751aad4df501653c0381a6ad2d2594f39fa411b8ff681104fb7489077c12865d75de7e823c32c41f01",
          "sha256": "42789faade618d530f858034360a68aa4b0a417931846992137a5b1ea4f4a969",
          "sha1": "21e722aeb667c6e32ed2936e80fc76f1963bb577",
          "md5": "ffc6e358f8001c2e5ddce320eb73fe3f"
        }
      ]
    }
  ]
}
