{
  "formatVersion": "1.1",
  "component": {
    "group": "com.imf.so",
    "module": "load-assets-7z",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "load-assets-7z-0.0.8.aar",
          "url": "load-assets-7z-0.0.8.aar",
          "size": 17135,
          "sha512": "acf936a30c0f1ac4f2b76eeb3948c0fcc88de7803e2bf65c100d01cfdb66129a822b3743362b60e887bbf606d60648a8acff0fe90522b244e564f4995cc4fc0d",
          "sha256": "2148e440f5fac83aa08ab2c4536859172ecd345487b621b249a28b914dc9aa8b",
          "sha1": "faf2cb781b59aafa84e88a49818ae5c6860e57f0",
          "md5": "181f0f431ce6a7c67f188050bb8169ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.imf.so",
          "module": "load-hook",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "com.imf.so",
          "module": "android-un7z",
          "version": {
            "requires": "0.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "load-assets-7z-0.0.8.aar",
          "url": "load-assets-7z-0.0.8.aar",
          "size": 17135,
          "sha512": "acf936a30c0f1ac4f2b76eeb3948c0fcc88de7803e2bf65c100d01cfdb66129a822b3743362b60e887bbf606d60648a8acff0fe90522b244e564f4995cc4fc0d",
          "sha256": "2148e440f5fac83aa08ab2c4536859172ecd345487b621b249a28b914dc9aa8b",
          "sha1": "faf2cb781b59aafa84e88a49818ae5c6860e57f0",
          "md5": "181f0f431ce6a7c67f188050bb8169ef"
        }
      ]
    }
  ]
}
