{
  "formatVersion": "1.1",
  "component": {
    "group": "com.imf.so",
    "module": "file-plugin",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "file-plugin-0.0.8.jar",
          "url": "file-plugin-0.0.8.jar",
          "size": 61137,
          "sha512": "8f9d608f07293d04045f7e77440b2575025d21d1d5332b21d881a8c1c2d8287b44c3ef6794097235e34d776cc14f84ddcbe0276ed1cd1a9806a58250d53a4f66",
          "sha256": "3b8d05fb5ed343397be4854807ada96e4065384867186a4c75c71ce85fc19892",
          "sha1": "4f2c4b488f1966ce5dbe3bc6106d0be9a7bd8967",
          "md5": "deef3511a89fd6179ff6fe35ecaf8f8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "file-plugin-0.0.8.jar",
          "url": "file-plugin-0.0.8.jar",
          "size": 61137,
          "sha512": "8f9d608f07293d04045f7e77440b2575025d21d1d5332b21d881a8c1c2d8287b44c3ef6794097235e34d776cc14f84ddcbe0276ed1cd1a9806a58250d53a4f66",
          "sha256": "3b8d05fb5ed343397be4854807ada96e4065384867186a4c75c71ce85fc19892",
          "sha1": "4f2c4b488f1966ce5dbe3bc6106d0be9a7bd8967",
          "md5": "deef3511a89fd6179ff6fe35ecaf8f8d"
        }
      ]
    }
  ]
}
