{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mainlxl.Android-So-Handler",
    "module": "load-hook-plugin",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "load-hook-plugin-0.0.12.jar",
          "url": "load-hook-plugin-0.0.12.jar",
          "size": 34337,
          "sha512": "51c5c216459aed3e15e8b58a2b06100703d51cd500a1389d16c009105e0737f75ea1021066d200d46e6ccb383018aa089bf4c9482843bad7391015ab70a66043",
          "sha256": "8ef3496f4a86beff80429578a6704ee4f1b9d2376930ba13348396e0b7b55fcb",
          "sha1": "4699b51a98acc8be3de213bcfd39f137bd663470",
          "md5": "7bf844e957d989d87038f7d9dfd599e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.3.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "load-hook-plugin-0.0.12.jar",
          "url": "load-hook-plugin-0.0.12.jar",
          "size": 34337,
          "sha512": "51c5c216459aed3e15e8b58a2b06100703d51cd500a1389d16c009105e0737f75ea1021066d200d46e6ccb383018aa089bf4c9482843bad7391015ab70a66043",
          "sha256": "8ef3496f4a86beff80429578a6704ee4f1b9d2376930ba13348396e0b7b55fcb",
          "sha1": "4699b51a98acc8be3de213bcfd39f137bd663470",
          "md5": "7bf844e957d989d87038f7d9dfd599e0"
        }
      ]
    }
  ]
}
