{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mainlxl.Android-So-Handler",
    "module": "load-hook-plugin",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "load-hook-plugin-0.0.12.jar",
          "url": "load-hook-plugin-0.0.12.jar",
          "size": 34337,
          "sha512": "04371c4991df66d132f0c5cff0bf83a0a93954e12109d1c9e5260a05b83ba1af3f1944bcb8e867d118b21911400044ce4b72820a3399a6c95a25f8464e5270b5",
          "sha256": "a416d6ad7db80ef0c240c148b702fbae02ae55e057007800e90160a770710129",
          "sha1": "77ee668d4b8b48b30459513a7f8edaf287d5fd0b",
          "md5": "814b7f9f043cabdf383cfd53a04c1de8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.3.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "load-hook-plugin-0.0.12.jar",
          "url": "load-hook-plugin-0.0.12.jar",
          "size": 34337,
          "sha512": "04371c4991df66d132f0c5cff0bf83a0a93954e12109d1c9e5260a05b83ba1af3f1944bcb8e867d118b21911400044ce4b72820a3399a6c95a25f8464e5270b5",
          "sha256": "a416d6ad7db80ef0c240c148b702fbae02ae55e057007800e90160a770710129",
          "sha1": "77ee668d4b8b48b30459513a7f8edaf287d5fd0b",
          "md5": "814b7f9f043cabdf383cfd53a04c1de8"
        }
      ]
    }
  ]
}
