{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mainlxl.Android-So-Handler",
    "module": "load-hook",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "load-hook-0.0.12.jar",
          "url": "load-hook-0.0.12.jar",
          "size": 2305,
          "sha512": "aeaf18d199c2a31fd339784f05fa5cc7cd41b101ff63629d8ce4d465849ff660693d3b921489c7356053894fede28ac9953a71df33b29dd1cff3017066679d46",
          "sha256": "eab0508f2ba7e27aa43a09a2c96712a06cd29daffc5eda985ed327cb09c343d1",
          "sha1": "868a2dfdfab3c3e34a0d1d899379c1e20187fc72",
          "md5": "70e23ebcffce9b0fd26db3d83626106f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "load-hook-0.0.12.jar",
          "url": "load-hook-0.0.12.jar",
          "size": 2305,
          "sha512": "aeaf18d199c2a31fd339784f05fa5cc7cd41b101ff63629d8ce4d465849ff660693d3b921489c7356053894fede28ac9953a71df33b29dd1cff3017066679d46",
          "sha256": "eab0508f2ba7e27aa43a09a2c96712a06cd29daffc5eda985ed327cb09c343d1",
          "sha1": "868a2dfdfab3c3e34a0d1d899379c1e20187fc72",
          "md5": "70e23ebcffce9b0fd26db3d83626106f"
        }
      ]
    }
  ]
}
